class DBException(Exception):...
class RedisException(Exception):...
class APIException(Exception):
    def __init__(self,errMsg) -> None:
        super().__init__()
        self.errMsg = errMsg

class SessionExpiredException(Exception):...